<?php
  
/**
 * Implemnts hook_webform_component_info().
 */
function os2forms_date_popup_webform_component_info() {
  $components = array();
  $components['date_popup'] = array(
    'label' => t('Date popup'),
    'description' => t('Create date popup as alaternative of standard webform date field.'),
    'features' => array(
      'csv' => TRUE,
      'email' => TRUE,
      'email_address' => FALSE,
      'email_name' => FALSE,
      'required' => FALSE,
      'title_display' => TRUE,
      'title_inline' => FALSE,
      'conditional' => FALSE,
      'group' => FALSE,
      'spam_analysis' => FALSE,
      'attachment' => FALSE,
    ),
    'file' => 'components/date_popup.inc',
  );
  return $components;
} 

function os2forms_date_popup_init(){
  if (!path_is_admin(current_path())) {
    drupal_add_js(drupal_get_path('module', 'os2forms_date_popup') . '/js/bootstrap-datepicker.min.js');
    drupal_add_js(drupal_get_path('module', 'os2forms_date_popup') . '/js/bootstrap-datepicker.da.min.js');
    drupal_add_js(drupal_get_path('module', 'os2forms_date_popup') . '/js/init.js');
  }
}